// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheSteward.Infrastructure.Data;

#nullable disable

namespace TheSteward.Infrastructure.Migrations
{
    [DbContext(typeof(TheStewardContext))]
    partial class TheStewardContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TheSteward.Core.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TheSteward.Core.Models.FinanceManagerModels.Budget", b =>
                {
                    b.Property<Guid>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BudgetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefaultBudget")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BudgetId");

                    b.HasIndex("HouseholdId");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("TheSteward.Core.Models.FinanceManagerModels.BudgetCategory", b =>
                {
                    b.Property<Guid>("BudgetCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BudgetCategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.HasKey("BudgetCategoryId");

                    b.HasIndex("BudgetId");

                    b.ToTable("BudgetCategories");
                });

            modelBuilder.Entity("TheSteward.Core.Models.FinanceManagerModels.BudgetSubCategory", b =>
                {
                    b.Property<Guid>("BudgetSubCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BudgetCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid");

                    b.Property<string>("BudgetSubCategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.HasKey("BudgetSubCategoryId");

                    b.HasIndex("BudgetCategoryId");

                    b.HasIndex("BudgetId");

                    b.ToTable("BudgetSubCategories");
                });

            modelBuilder.Entity("TheSteward.Core.Models.FinanceManagerModels.Credit", b =>
                {
                    b.Property<Guid>("CreditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreditName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CreditType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<decimal>("EstMonthlyInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EstYearlyInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PaymentDay")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentFrequency")
                        .HasColumnType("integer");

                    b.HasKey("CreditId");

                    b.HasIndex("BudgetId");

                    b.HasIndex("ExpenseId")
                        .IsUnique();

                    b.ToTable("Credits");
                });

            modelBuilder.Entity("TheSteward.Core.Models.FinanceManagerModels.Expense", b =>
                {
                    b.Property<Guid>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountDue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BudgetCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BudgetSubCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreditId")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("DueDay")
                        .HasColumnType("integer");

                    b.Property<string>("ExpenseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InvestmentId")
                        .HasColumnType("uuid");

                    b.HasKey("ExpenseId");

                    b.HasIndex("BudgetCategoryId");

                    b.HasIndex("BudgetId");

                    b.HasIndex("BudgetSubCategoryId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("TheSteward.Core.Models.FinanceManagerModels.Income", b =>
                {
                    b.Property<Guid>("IncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<decimal>("EstFederalIncomeTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EstStateIncomeTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FilingStatus")
                        .HasColumnType("integer");

                    b.Property<int>("IncomeFrequency")
                        .HasColumnType("integer");

                    b.Property<string>("IncomeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("MonthlyNetIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PayCheckGross")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("YearlyGrossSalary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IncomeId");

                    b.HasIndex("BudgetId");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("TheSteward.Core.Models.FinanceManagerModels.Investment", b =>
                {
                    b.Property<Guid>("InvestmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ContributionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ContributionFrequency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<decimal>("EstYearlyGrowth")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ExpenseId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("InvestmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("InvestmentId");

                    b.HasIndex("BudgetId");

                    b.HasIndex("ExpenseId")
                        .IsUnique();

                    b.ToTable("Investments");
                });

            modelBuilder.Entity("TheSteward.Core.Models.HouseholdModels.Household", b =>
                {
                    b.Property<Guid>("HouseholdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("HasFileManagerAccess")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasFinanceManagerAccess")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasKitchenManagerAccess")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasTaskManagerAccess")
                        .HasColumnType("boolean");

                    b.Property<string>("HouseholdName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsHouseholdActive")
                        .HasColumnType("boolean");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HouseholdId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Households");
                });

            modelBuilder.Entity("TheSteward.Core.Models.HouseholdModels.HouseholdInvitation", b =>
                {
                    b.Property<Guid>("InvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("InvitedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("InvitedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvitedUserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean");

                    b.HasKey("InvitationId");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("InvitedByUserId");

                    b.ToTable("HouseholdInvitations");
                });

            modelBuilder.Entity("TheSteward.Core.Models.HouseholdModels.UserHousehold", b =>
                {
                    b.Property<Guid>("UserHouseholdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DefaultBudgetId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasAdminPermissions")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasFileManagerReadPermission")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasFileManagerWritePermission")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasFinanceManagerReadPermission")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasFinanceManagerWritePermission")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasKitchenManagerReadPermission")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasKitchenManagerWritePermission")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasTaskManagerCompletePermission")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasTaskManagerReadPermission")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasTaskManagerWritePermission")
                        .HasColumnType("boolean");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefaultUserHousehold")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHouseholdOwner")
                        .HasColumnType("boolean");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("UserHouseholdId");

                    b.HasIndex("DefaultBudgetId");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("UserId");

                    b.ToTable("UserHouseholds");
                });

            modelBuilder.Entity("TheSteward.Core.Models.TaskManagerModels.RecurrenceRule", b =>
                {
                    b.Property<Guid>("RecurrenceRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IntervalDays")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastGeneratedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RecurrenceDays")
                        .HasColumnType("integer");

                    b.Property<int>("RecurrenceFrequency")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RecurrenceRuleId");

                    b.ToTable("RecurrenceRules");
                });

            modelBuilder.Entity("TheSteward.Core.Models.TaskManagerModels.TaskItem", b =>
                {
                    b.Property<Guid>("TaskItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedToUserHouseholdId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserHouseholdId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ExpenseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RecurrenceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaskItemCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("TaskItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TaskItemId");

                    b.HasIndex("AssignedToUserHouseholdId");

                    b.HasIndex("CreatedByUserHouseholdId");

                    b.HasIndex("ExpenseId");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("RecurrenceId");

                    b.HasIndex("TaskItemCategoryId");

                    b.ToTable("TaskItems");
                });

            modelBuilder.Entity("TheSteward.Core.Models.TaskManagerModels.TaskItemCategory", b =>
                {
                    b.Property<Guid>("TaskItemCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconName")
                        .HasColumnType("text");

                    b.Property<string>("TaskItemCategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TaskItemCategoryId");

                    b.ToTable("TaskItemsCategories");
                });

            modelBuilder.Entity("TheSteward.Core.Models.TaskManagerModels.TaskItemOccurrence", b =>
                {
                    b.Property<Guid>("TaskItemOccurrenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompletedByUserHouseholdId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ScheduledDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uuid");

                    b.HasKey("TaskItemOccurrenceId");

                    b.HasIndex("TaskItemId");

                    b.ToTable("TaskItemOccurrences");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TheSteward.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TheSteward.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheSteward.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TheSteward.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheSteward.Core.Models.FinanceManagerModels.Budget", b =>
                {
                    b.HasOne("TheSteward.Core.Models.HouseholdModels.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("TheSteward.Core.Models.FinanceManagerModels.BudgetCategory", b =>
                {
                    b.HasOne("TheSteward.Core.Models.FinanceManagerModels.Budget", "Budget")
                        .WithMany("BudgetCategories")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("TheSteward.Core.Models.FinanceManagerModels.BudgetSubCategory", b =>
                {
                    b.HasOne("TheSteward.Core.Models.FinanceManagerModels.BudgetCategory", "BudgetCategory")
                        .WithMany("BudgetSubCategories")
                        .HasForeignKey("BudgetCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheSteward.Core.Models.FinanceManagerModels.Budget", "Budget")
                        .WithMany()
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");

                    b.Navigation("BudgetCategory");
                });

            modelBuilder.Entity("TheSteward.Core.Models.FinanceManagerModels.Credit", b =>
                {
                    b.HasOne("TheSteward.Core.Models.FinanceManagerModels.Budget", "Budget")
                        .WithMany("Credits")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheSteward.Core.Models.FinanceManagerModels.Expense", "LinkedExpense")
                        .WithOne("LinkedCredit")
                        .HasForeignKey("TheSteward.Core.Models.FinanceManagerModels.Credit", "ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");

                    b.Navigation("LinkedExpense");
                });

            modelBuilder.Entity("TheSteward.Core.Models.FinanceManagerModels.Expense", b =>
                {
                    b.HasOne("TheSteward.Core.Models.FinanceManagerModels.BudgetCategory", "BudgetCategory")
                        .WithMany()
                        .HasForeignKey("BudgetCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheSteward.Core.Models.FinanceManagerModels.Budget", "Budget")
                        .WithMany("Expenses")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheSteward.Core.Models.FinanceManagerModels.BudgetSubCategory", "BudgetSubCategory")
                        .WithMany()
                        .HasForeignKey("BudgetSubCategoryId");

                    b.Navigation("Budget");

                    b.Navigation("BudgetCategory");

                    b.Navigation("BudgetSubCategory");
                });

            modelBuilder.Entity("TheSteward.Core.Models.FinanceManagerModels.Income", b =>
                {
                    b.HasOne("TheSteward.Core.Models.FinanceManagerModels.Budget", "Budget")
                        .WithMany("Incomes")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("TheSteward.Core.Models.FinanceManagerModels.Investment", b =>
                {
                    b.HasOne("TheSteward.Core.Models.FinanceManagerModels.Budget", "Budget")
                        .WithMany("Investments")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheSteward.Core.Models.FinanceManagerModels.Expense", "LinkedExpense")
                        .WithOne("LinkedInvestment")
                        .HasForeignKey("TheSteward.Core.Models.FinanceManagerModels.Investment", "ExpenseId");

                    b.Navigation("Budget");

                    b.Navigation("LinkedExpense");
                });

            modelBuilder.Entity("TheSteward.Core.Models.HouseholdModels.Household", b =>
                {
                    b.HasOne("TheSteward.Core.Models.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TheSteward.Core.Models.HouseholdModels.HouseholdInvitation", b =>
                {
                    b.HasOne("TheSteward.Core.Models.HouseholdModels.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheSteward.Core.Models.ApplicationUser", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("InvitedByUser");
                });

            modelBuilder.Entity("TheSteward.Core.Models.HouseholdModels.UserHousehold", b =>
                {
                    b.HasOne("TheSteward.Core.Models.FinanceManagerModels.Budget", "DefaultBudget")
                        .WithMany()
                        .HasForeignKey("DefaultBudgetId");

                    b.HasOne("TheSteward.Core.Models.HouseholdModels.Household", "Household")
                        .WithMany("UserHouseholds")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheSteward.Core.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefaultBudget");

                    b.Navigation("Household");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheSteward.Core.Models.TaskManagerModels.TaskItem", b =>
                {
                    b.HasOne("TheSteward.Core.Models.HouseholdModels.UserHousehold", "AssignedToUserHousehold")
                        .WithMany()
                        .HasForeignKey("AssignedToUserHouseholdId");

                    b.HasOne("TheSteward.Core.Models.HouseholdModels.UserHousehold", "CreatedByUserHousehold")
                        .WithMany()
                        .HasForeignKey("CreatedByUserHouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheSteward.Core.Models.FinanceManagerModels.Expense", "RelatedExpense")
                        .WithMany()
                        .HasForeignKey("ExpenseId");

                    b.HasOne("TheSteward.Core.Models.HouseholdModels.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheSteward.Core.Models.TaskManagerModels.RecurrenceRule", "RecurrenceRule")
                        .WithMany("TaskItems")
                        .HasForeignKey("RecurrenceId");

                    b.HasOne("TheSteward.Core.Models.TaskManagerModels.TaskItemCategory", "TaskItemCategory")
                        .WithMany("TaskItems")
                        .HasForeignKey("TaskItemCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedToUserHousehold");

                    b.Navigation("CreatedByUserHousehold");

                    b.Navigation("Household");

                    b.Navigation("RecurrenceRule");

                    b.Navigation("RelatedExpense");

                    b.Navigation("TaskItemCategory");
                });

            modelBuilder.Entity("TheSteward.Core.Models.TaskManagerModels.TaskItemOccurrence", b =>
                {
                    b.HasOne("TheSteward.Core.Models.TaskManagerModels.TaskItem", "TaskItem")
                        .WithMany()
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("TheSteward.Core.Models.FinanceManagerModels.Budget", b =>
                {
                    b.Navigation("BudgetCategories");

                    b.Navigation("Credits");

                    b.Navigation("Expenses");

                    b.Navigation("Incomes");

                    b.Navigation("Investments");
                });

            modelBuilder.Entity("TheSteward.Core.Models.FinanceManagerModels.BudgetCategory", b =>
                {
                    b.Navigation("BudgetSubCategories");
                });

            modelBuilder.Entity("TheSteward.Core.Models.FinanceManagerModels.Expense", b =>
                {
                    b.Navigation("LinkedCredit");

                    b.Navigation("LinkedInvestment");
                });

            modelBuilder.Entity("TheSteward.Core.Models.HouseholdModels.Household", b =>
                {
                    b.Navigation("UserHouseholds");
                });

            modelBuilder.Entity("TheSteward.Core.Models.TaskManagerModels.RecurrenceRule", b =>
                {
                    b.Navigation("TaskItems");
                });

            modelBuilder.Entity("TheSteward.Core.Models.TaskManagerModels.TaskItemCategory", b =>
                {
                    b.Navigation("TaskItems");
                });
#pragma warning restore 612, 618
        }
    }
}
