steps:
 # Step 1 — Build the Docker image
 - name: 'gcr.io/cloud-builders/docker'
   args:
     - 'build'
     - '-t'
     - 'us-east1-docker.pkg.dev/thesteward-506018/thesteward-repo/thesteward:$COMMIT_SHA'
     - '-t'
     - 'us-east1-docker.pkg.dev/thesteward-506018/thesteward-repo/thesteward:latest'
     - '.'
 # Step 2 — Push versioned image
 - name: 'gcr.io/cloud-builders/docker'
   args:
     - 'push'
     - 'us-east1-docker.pkg.dev/thesteward-506018/thesteward-repo/thesteward:$COMMIT_SHA'
 # Step 3 — Push latest tag
 - name: 'gcr.io/cloud-builders/docker'
   args:
     - 'push'
     - 'us-east1-docker.pkg.dev/thesteward-506018/thesteward-repo/thesteward:latest'
 # Step 4 — Deploy to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
     - 'run'
     - 'deploy'
     - 'thesteward'
     - '--image'
     - 'us-east1-docker.pkg.dev/thesteward-506018/thesteward-repo/thesteward:$COMMIT_SHA'
     - '--region'
     - 'us-east1'
     - '--platform'
     - 'managed'
     - '--allow-unauthenticated'
     - '--set-secrets'
     - 'ConnectionStrings__DefaultConnection=thesteward-connection-string:latest'
     - '--min-instances'
     - '1'
     - '--max-instances'
     - '5'
images:
 - 'us-east1-docker.pkg.dev/thesteward-506018/thesteward-repo/thesteward:$COMMIT_SHA'
 - 'us-east1-docker.pkg.dev/thesteward-506018/thesteward-repo/thesteward:latest'
options:
 logging: CLOUD_LOGGING_ONLY
